name: Tests

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/ci.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # install torch first because torch_scatter needs it
          pip install torch==1.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
          pip install -r requirements.txt
          pip install .

      - name: Run Tests
        run: |
          python -m pytest
